version: "3"
services:
  ui:
    ports: 
      - "8088:80"
  simple:
    ports: 
      - "8080:8080"
  notifications:
    ports: 
      - "8083:8080"
  users:
    ports: 
      - "8084:8080"
  proxy:
  jms:
    ports:
      - "8081:8080"
  db:
    ports:
      - "3306:3306"
